[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = huge_app.csv
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.flash_size = 4MB
board_build.flash_mode = dio
framework = arduino
monitor_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=0

lib_deps =
    Preferences
    WebServer
