[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D AAC_CODEC_SUPPORT=1
    -I lib/ESP32-A2DP/src
    -I lib/arduino-audio-tools/src
